package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class Controller {
	@FXML
	private TextField txt;

	// Event Listener on Button.onAction
	@FXML
	public void cambiarTexto(ActionEvent event) {
		// TODO Autogenerated
		String texto = txt.getText();
		txt.setText("Hola");
	}
}
